name: main

on:
  push:
    branches:
      - main

jobs:
  sync_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache do pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalando dependências
        working-directory: workflows
        run: pip install -r requirements.txt

      - name: Verificando existência do main.py
        run: test -f workflows/main.py

      - name: Sincronizando Jobs com Databricks
        env:
          host: ${{ secrets.DATABRICKS_HOST }}
          tokendatabricks: ${{ secrets.DATABRICKS_TOKEN }}
        working-directory: workflows
        run: python main.py
